### ISSUE TITLE
IOS DatePicker Cancel Button Problem

### ISSUE THREAD

**Issue by balachandranmca** [skwasjer/skwas-cordova-plugin-datetimepicker#23] opened 2018-07-24 07:00 UTC
In IOS Mobile, if you click DatePicker then you click cancel button and again you click DatePicker default date is change to January month

**Comment by skwasjer** [comment] 2018-07-24 16:09
Can you attach some sample code illustrating the problem? Also, which iOS version?

**Comment by balachandranmca** [comment] 2018-07-31 03:54
IOS 10

**Comment by skwasjer** [comment] 2018-09-19 16:38
Unable to reproduce, closing due to lack of context provided. @balachandranmca if you can be more specific and provide example code that illustrates the problem, I am willing to look into it again

**Closed as completed by skwasjer** 2018-09-19 16:38 UTC

**Comment by jeganwbc** [comment] 2019-09-11 10:06
**First Time Click the Datepicker**
![](https://lh3.googleusercontent.com/-G-OChf0mm5w/XXjG9eFwJyI/AAAAAAAAC1M/MVtSbLXhO9YLcJl7oMVTvdarVij1JFZUQCK8BGAsYHg/s0/2019-09-11.jpg)

**Then cancel and open datepicker**
![](https://lh3.googleusercontent.com/-mY8IQ-iQ78o/XXjG8WBKk5I/AAAAAAAAC1I/ngNoa0XgVM8Wjh3kzjfEi5ZM6ADndNQ8QCK8BGAsYHg/s0/2019-09-11.jpg)
