### ISSUE TITLE
java.lang.NoClassDefFoundError: com.skwas.cordova.datetimepicker.DateTimePicker Error in Redmi Mobiles

### ISSUE THREAD

**Issue by jeganwbc** [skwasjer/skwas-cordova-plugin-datetimepicker#32] opened 2019-08-27 12:44 UTC
I am working with various mobile models. All are working fine. But Redmi (Mi) Mobile model phones not shows the datepicker. It's shows a error while i am debugging.

![image](https://user-images.githubusercontent.com/28730476/63772292-6e53b380-c8f6-11e9-80f4-29182df99f17.png)

**Comment by skwasjer** [comment] 2019-08-27 16:33
I don't know why this does not work. It seems like the plugin java file(s) is not added/compiled, which typically is the case for this exception. But I don't know how to explain why it does work for other devices. Perhaps some kind of dependency is missing?

All I can suggest is verify that:
- `res/xml/config.xml` contains the DateTimePicker feature:  
  
  ```
  <feature name="DateTimePicker">
      <param name="android-package" value="com.skwas.cordova.datetimepicker.DateTimePicker" />
  </feature>
   ```
- the Java source files are in the `platforms/android/../com/skwas/cordova/datetimepicker` folder (DatePickerDialog.java, DateTimePicker.java, TimePickerDialog.java)

What version of Cordova are you using, because some of the platform specific locations have changed over time.

**Comment by jeganwbc** [comment] 2019-08-29 12:55
Config.xml found that code feature name datetimepicker.

the Java source files location not changed it's in same location.
**File Path:**
android\app\src\main\java\com\skwas\cordova\datetimepicker\

**Comment by skwasjer** [comment] 2019-09-26 17:22
I've done some tests and this seems to be a duplicate of #31 (Android API level).

**Closed as completed by skwasjer** 2019-09-26 17:22 UTC
Labels: bug, duplicate

**Comment by jeganwbc** [comment] 2019-09-30 07:09
@skwasjer Thanks ..! It's working..!
